import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="assets/img/logo/titile.png"
          type="image/x-icon"
        />

        <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/css/fontawesome.css" />
        <link rel="stylesheet" href="assets/css/magnific-popup.css" />
        <link rel="stylesheet" href="assets/css/nice-select.css" />
        <link rel="stylesheet" href="assets/css/slick-slider.css" />
        <link rel="stylesheet" href="assets/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="assets/css/aos.css" />
        <link rel="stylesheet" href="assets/css/mobile-menu.css" />
        <link rel="stylesheet" href="assets/css/main.css" />

        <script src="assets/js/jquery-3-7-1.min.js"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/aos.js"></script>
        <script src="assets/js/fontawesome.js"></script>
        <script src="assets/js/jquery.countup.js"></script>
        <script src="assets/js/mobile-menu.js"></script>
        <script src="assets/js/jquery.magnific-popup.js"></script>
        <script src="assets/js/owl.carousel.min.js"></script>
        <script src="assets/js/slick-slider.js"></script>
        <script src="assets/js/gsap.min.js"></script>
        <script src="assets/js/ScrollTrigger.min.js"></script>
        <script src="assets/js/Splitetext.js"></script>
        <script src="assets/js/text-animation.js"></script>
        <script src="assets/js/SmoothScroll.js"></script>
        <script src="assets/js/jquery.lineProgressbar.js"></script>
        <script src="assets/js/ripple-btn.js"></script>
        <script src="assets/js/main.js"></script>
      </body>
    </html>
  );
}
